from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
# request paramaeter automaticall generated by Django
def index(request):

    #return HttpResponse('Hello World!')
    # now we have to return html file as response 
    return render(request, 'meetups/index.html')
