from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
# request paramaeter automaticall generated by Django
def index(request):

    # return HttpResponse('Hello World!')
    # now we have to return html file as response

    # dynamic data show on template
    meetups = [
        {'title': 'First Meetups', 'location': 'New York', 'slug': 'a-frist-meetups'},
        {'title': 'Second Meetups', 'location': 'Paris', 'slug': 'a-second-meetups'}
    ]
    return render(request, 'meetups/index.html', {
        'meetups': meetups,
        'show_meetups': False
    })


def meetup_details(request,meetup_slug):
    print(meetup_slug)
    selected_meetup = {
        'title':'Here is First Meetup',
        'description':'This is description for second meetups'
    }
    return render(request, 'meetups/meetup-details.html',
                  {
                      'selected_meetup': selected_meetup
                  })
