from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
# request paramaeter automaticall generated by Django
def index(request):

    #return HttpResponse('Hello World!')
    # now we have to return html file as response 
    
    # dynamic data show on template
    meetups= [
        {'title':'this is first Meetups'},
        {'title':'this is second Meetups'}
    ]
    return render(request, 'meetups/index.html',{
        'meetups':meetups,
        'show_meetups':False
    })
